name: BBC Young Reporter | Reading School
title: BBC Young Reporter | Reading School
defaults:
  -
    scope:
      path: ""
    values:
      layout: "home"
  
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
collections:
  articles:
    output: true