name: BBC Young Reporter | Reading School
title: BBC Young Reporter | Reading School
parallax-speed: 0.5
defaults:
  -
    scope:
      path: ""
    values:
      layout: "year"
  
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "image-article"
collections:
  articles:
    output: true